### ISSUE TITLE
[Feature Request] Replace ProtocolLib with packetevents

### ISSUE THREAD

**Issue by R00tB33rMan** [stonar96/RayTraceAntiXray#22]
Effectively, as the title states. Although this plugin performs substantially well compared to alternatives, utilizing packetevents would dramatically improve its performance. Although I expect this to be difficult/tedious, it'd likely incentivize more users to utilize this resource on more extensive production networks that exceed 300 concurrent players on a single instance.

**Comment by stonar96** [comment]
Hi @R00tB33rMan I've once attempted this. The problem was that I wasn't able to get the original NMS packet instance from their API, which I need for reference equality checks in RayTraceAntiXray. If someone finds a simple solution to this problem, feel free to contribute.

See also https://github.com/retrooper/packetevents/issues/489
