### ISSUE TITLE
No support for hiding wall torch

### ISSUE THREAD

**Issue by Fypsilon** [stonar96/RayTraceAntiXray#28]
I tried hiding wall_torch and torch so that player could not xray towards Mineshaft torches but even when adding it in the normal AntiXray's config as well as the plugin config, they cannot be hidden. Every other block besides entities of course seems to be working. If I am using wrong item ID please let me know the correct ID.

**Comment by stonar96** [comment]
Hi, the ID seems to be correct. I suspect that the torches are actually hidden but the lighting engine sends block updates due to lighting updates. If so, unfortunately there's not much I can do about this, especially when the server's built-in Anti-Xray can't even handle this. Also note that RayTraceAntiXray (as most other Anti-Xrays) is about hiding ores. Ray tracing blocks that are commonly placed by players (or non-valueable blocks in general) isn't a great idea in the first place because it requires server resources. I'm not saying you can't, but that's not intended.
